config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations
  has_many :attendees, through: :registrations
  has_many :comments
end

app/models/registration.rb
class Registration < ApplicationRecord
 belongs_to :user
 belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations
  has_many :events, through: :registrations
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_event
  before_action :find_comment, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.event_id = @event.id
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    
    if @comment.update(comment_params)
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @events = Event.all.order("created_at DESC")
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event has been created successfully!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "Event has been updated successfully!"
      redirect_to event_path(@event)
    else
      flash[:error] = 'Event has not been updated !'
      render 'edit'
    end
  end

  def destroy
    if @event.destroy
      flash[:notice] = "Event has been deleted successfully!"
      redirect_to root_path
    else
      flash[:error] = "Event has not been deleted"
      redirect_to root_path
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :place, :description, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= comment.text %>

app/views/comments/_form.html.erb
<%= simple_form_for([@event, @event.comments.build]) do |f| %>
  <%= f.input :text %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Review</h1>

		<% if @comment.user_id == current_user.id %>

 			<%= simple_form_for([@event, @comment]) do |f| %>
 				<%= f.input :text %>
 				<%= f.button :submit, :class => "btn-custom2" %>
 			<% end %>

 		<% else %>

 			<h3>You're not allowed to edit this comment</h3>

 		<% end %>

app/views/comments/new.html.erb
<div class="container">
	<%= render 'form' %>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :date %>
	<%= f.input :place %>
    <%= f.button :submit, class: " btn btn-success" %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
	<h1>Editing Event</h1>

	<p><%= render 'form', route: @event %></p>
	<p><%= link_to 'Show', @event, class: "btn btn-primary active" %>
	<%= link_to 'Back', events_path, class: "btn btn-primary active" %></p>
</div>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <div class="col-md-3">
    <h1><%= event.name %></h1>
    <%= event.description %>
    <%= event.date %>
    <%= link_to 'Show', event_path(event), class: "btn btn-info" %>
  </div>
<% end %>

app/views/events/new.html.erb
<div class="container">
	<h1>New Event</h1>
	<p><%= render 'form', route: @event %></p>
	<p><%= link_to 'Back', events_path, class: "btn btn-primary active" %></p>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="well">
    <div>
	  <h2>Name: <%= @event.name %></h2>
	  <h2>Descritpion: <%= @event.description %></h2>
	  <h2>Time and date: <%= @event.date %></h2>
	  <h2>Place: <%= @event.place %></h2>
	</div>
    <%= link_to "add comment", new_event_comment_path(@event), class: "btn btn-primary active" %>
    <%= render @event.comments %>
      <%= link_to 'Back', events_path, class: "btn btn-primary active" %>
      <%= link_to 'Edit', edit_event_path(@event), class: "btn btn-primary active" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>